language: node_js
node_js: 6
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g bower polymer-cli
- bower install
script: echo "Deploying!"
before_deploy: polymer build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfest2017-8f458
  token:
    secure: LsXueU4GjrnhjYgEMcpioL3LYFK5yEBO/Z4yABsjLY3xD5pXF6Re7ZXxyD3ZzH7QmkAAqUpuTXE2wRcLg27/pdkMafWzEnixZlNFlnJXGE6SCXmeI2tOPgFMNCemQjbOrHIVFFdM5fOLmiHC9VWEtHZ+UIJz12vupN+wTjlqeh4YuPsKvAsmcZS9gjm7awcshWY33VaWGLHWdJBEmfR/pRblx+QhSmt078GRlXwYwEo7Ch8yXmbRJia9kKsNS16U0zoqps6bH3q2HwWNz4l4u/IrBS9tdaXmKBypZ4w2fB6evt7wJ7L2TYuILOMy4nHmhj3yW8kSa8LgT3Xa3hDZLkwL/fXiyjALsApHJA7d8Pswe0CIEEUVUvBentgUSnNdsUS0OI55auSJ8CKu9amCyj8WVeAfxTq4QH2W4dgol426PF40LlxiWwjxJGTmkwLsDcwI5ervyliCuMrP1z8vtgbIJbVZEQ284e3OE54mMIIscPLcQWZ+mTVrBdnVjGoxWK9AnkHRR7SeXqZ0GgGtm3+gnXE6kenm04nvreXLN3rKaH5Cx4tJfIqnQbgOMIhxxmtEpztGHtDsZxY4HNQXNuEb3wmeupl9ryKniYoD5tJ1tzOREQ0NzYAlabSEIH2MP9/Bb00i/ryPeMTJUyRlMrzqxZE2EOBrKGQAcQ72yWk=
